name: build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: bazelisk build //...

      - name: run ut
        run: ./bazel-bin/art_unittest
